### ISSUE TITLE
Foundry 0.7.4 crash during launch

### ISSUE THREAD

**Issue by Nimda99** [CStuartEKerrigan/WFRP-e4e-4e-FVTT#1]
After the most recent 0.7.4 update, aware this is not stable, FoundryVTT fails to launch with eye for and eye or making the rounds modules present.  As the menu does not load you cannot remove/update the module and the only way to fix is to move the module folder out of your data/modules folder.

**Comment by CStuartEKerrigan** [comment]
Updated module to support 0.7.6 now.
